package com.example.damasfx.Modelo;

public enum ResidenceCountry {
    ALEMANIA, AUSTRIA, BÉLGICA, BULGARIA, CHIPRE, CROACIA, DINAMARCA, ESLOVAQUIA, ESLOVENIA, ESPAÑA, ESTONIA, FINLANDIA, FRANCIA, GRECIA, HUNGRÍA, IRLANDA, ITALIA, LETONIA, LITUANIA, LUXEMBURGO, MALTA, POLONIA, PORTUGAL, RUMANÍA, SUECIA
}
